language: java

jdk:
  - openjdk8

services:
  - elasticsearch

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.6.1.deb && sudo dpkg -i --force-confnew elasticsearch-6.6.1.deb && sudo service elasticsearch restart
  - bash create_elasticsearch_index.sh

script: mvn clean test -Dspring.profiles.active=travis

cache:
  directories:
    - $HOME/.m2
