server:
  port: 8080

spring:
  profiles:
    active: docker
  data:
    elasticsearch:
      repositories:
        enabled: true
  datasource:
    url: jdbc:mysql://mysql:3306/tourist?useUnicode=true&characterEncoding=utf-8
    username: root
    password:
  banner:
    image:
      location: classpath*:banner.txt

mybatis:
  mapper-locations:
    - classpath:dao/*.xml

logging:
  pattern:
    console: "%date{yyyy-MM-dd HH:mm:ss.SSS,Asia/Shanghai} %X{clientIp}-%X{requestId}-%X{userId} %highlight(%-5level) [%t] %logger{36} : %m%n%wEx"
    file: "%date{yyyy-MM-dd HH:mm:ss.SSS,Asia/Shanghai} %X{clientIp}-%X{requestId}-%X{userId} %highlight(%-5level) [%t] %logger{36} : %m%n%wEx"

  level:
    root: ERROR
    org.springframework.web: ERROR
    com.wangsiqian.tourist: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: ["health", "env", "beans", "info"]

tourist:
  admin:
    role: "admin"
    username: "wangsiqian"
    password: "wangsiqian"
  elasticsearch:
    hostAndPort: "elasticsearch:9200"
