spring:
  devtools:
    restart:
      enabled: false

logging:
  file:
    path: /var/log/spring-boot-template.log
  pattern:
    console: "%date{yyyy-MM-dd HH:mm:ss.SSS,Asia/Shanghai} %X{clientIp}-%X{requestId}-%X{userId} %highlight(%-5level) [%t] %logger{36} : %m%n%wEx"
    file: "%date{yyyy-MM-dd HH:mm:ss.SSS,Asia/Shanghai} %X{clientIp}-%X{requestId}-%X{userId} %highlight(%-5level) [%t] %logger{36} : %m%n%wEx"
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.wangsiqian.template: DEBUG
