spring:
  datasource:
    url: jdbc:mysql://localhost:3307/tourist?useUnicode=true&characterEncoding=utf-8
    username: root
    password:

tourist:
  admin:
    role: "admin"
    username: "wangsiqian"
    password: "wangsiqian"
  elasticsearch:
    hostAndPort: "localhost:9200"
